// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: dbrpc.proto

// 定义包名

package protoMsg

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type L2D_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *L2D_Login) Reset() {
	*x = L2D_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2D_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2D_Login) ProtoMessage() {}

func (x *L2D_Login) ProtoReflect() protoreflect.Message {
	mi := &file_dbrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2D_Login.ProtoReflect.Descriptor instead.
func (*L2D_Login) Descriptor() ([]byte, []int) {
	return file_dbrpc_proto_rawDescGZIP(), []int{0}
}

func (x *L2D_Login) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *L2D_Login) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type D2L_UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID   int64  `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Score    int64  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Account  string `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Lv       int32  `protobuf:"varint,6,opt,name=lv,proto3" json:"lv,omitempty"`
}

func (x *D2L_UserInfo) Reset() {
	*x = D2L_UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *D2L_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*D2L_UserInfo) ProtoMessage() {}

func (x *D2L_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dbrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use D2L_UserInfo.ProtoReflect.Descriptor instead.
func (*D2L_UserInfo) Descriptor() ([]byte, []int) {
	return file_dbrpc_proto_rawDescGZIP(), []int{1}
}

func (x *D2L_UserInfo) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *D2L_UserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *D2L_UserInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *D2L_UserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *D2L_UserInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *D2L_UserInfo) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

var File_dbrpc_proto protoreflect.FileDescriptor

var file_dbrpc_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x62, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x73, 0x67, 0x22, 0x41, 0x0a, 0x09, 0x4c, 0x32, 0x44, 0x5f, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x9e, 0x01, 0x0a, 0x0c, 0x44,
	0x32, 0x4c, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6c,
	0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x32, 0x4e, 0x0a, 0x0c, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x42, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x73, 0x67, 0x2e, 0x4c, 0x32, 0x44, 0x5f, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x73, 0x67, 0x2e, 0x44, 0x32, 0x4c,
	0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_dbrpc_proto_rawDescOnce sync.Once
	file_dbrpc_proto_rawDescData = file_dbrpc_proto_rawDesc
)

func file_dbrpc_proto_rawDescGZIP() []byte {
	file_dbrpc_proto_rawDescOnce.Do(func() {
		file_dbrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_dbrpc_proto_rawDescData)
	})
	return file_dbrpc_proto_rawDescData
}

var file_dbrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dbrpc_proto_goTypes = []interface{}{
	(*L2D_Login)(nil),    // 0: protoMsg.L2D_Login
	(*D2L_UserInfo)(nil), // 1: protoMsg.D2L_UserInfo
}
var file_dbrpc_proto_depIdxs = []int32{
	0, // 0: protoMsg.LoginService.PlayerDBLogin:input_type -> protoMsg.L2D_Login
	1, // 1: protoMsg.LoginService.PlayerDBLogin:output_type -> protoMsg.D2L_UserInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dbrpc_proto_init() }
func file_dbrpc_proto_init() {
	if File_dbrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dbrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2D_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*D2L_UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dbrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dbrpc_proto_goTypes,
		DependencyIndexes: file_dbrpc_proto_depIdxs,
		MessageInfos:      file_dbrpc_proto_msgTypes,
	}.Build()
	File_dbrpc_proto = out.File
	file_dbrpc_proto_rawDesc = nil
	file_dbrpc_proto_goTypes = nil
	file_dbrpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginServiceClient interface {
	PlayerDBLogin(ctx context.Context, in *L2D_Login, opts ...grpc.CallOption) (*D2L_UserInfo, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) PlayerDBLogin(ctx context.Context, in *L2D_Login, opts ...grpc.CallOption) (*D2L_UserInfo, error) {
	out := new(D2L_UserInfo)
	err := c.cc.Invoke(ctx, "/protoMsg.LoginService/PlayerDBLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
type LoginServiceServer interface {
	PlayerDBLogin(context.Context, *L2D_Login) (*D2L_UserInfo, error)
}

// UnimplementedLoginServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLoginServiceServer struct {
}

func (*UnimplementedLoginServiceServer) PlayerDBLogin(context.Context, *L2D_Login) (*D2L_UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerDBLogin not implemented")
}

func RegisterLoginServiceServer(s *grpc.Server, srv LoginServiceServer) {
	s.RegisterService(&_LoginService_serviceDesc, srv)
}

func _LoginService_PlayerDBLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(L2D_Login)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).PlayerDBLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoMsg.LoginService/PlayerDBLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).PlayerDBLogin(ctx, req.(*L2D_Login))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoMsg.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayerDBLogin",
			Handler:    _LoginService_PlayerDBLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbrpc.proto",
}
